### ISSUE TITLE
Upgrade to new trace.moe API

### ISSUE THREAD

**Issue by soruly** [irevenko/what-anime-cli#4]
Hi, just want to notify you the new trace.moe API is out. Please take a look and update your program, otherwise it will be broken when the old API deprecates. You can find the docs of the new API with migration guide at https://github.com/soruly/trace.moe-api

**Comment by irevenko** [comment]
thanks for notifying 😅

**Comment by irevenko** [comment]
@soruly i was curios why you removed `at` and `season` fields?

**Comment by soruly** [comment]
Usually users doesn't care which moment the screenshot is "at", they'll start looking from start of the scene anyway. Besides, the frame deduplication algorithm uses first frame of the scene as reference. So you can consider the "from" the same as "at". And the difference between "from" and "to" typically doesn't last longer than a few seconds. This accuracy in time code should be enough for human.
The season field has been my own way of groupings according to my own personal perference. Some anime should be classified as ONA but instead put into OVA, or using yyyy-mm. Or anime airing from March being categorized to Janurary. It maybe confusing for users to look for that anime with that information. If you need this info, you can [query Anilist API](https://anilist.co/graphiql?query=query%20(%24ids%3A%20%5BInt%5D)%20%7B%0A%20%20Page(page%3A%201%2C%20perPage%3A%2050)%20%7B%0A%20%20%20%20media(id_in%3A%20%24ids%2C%20type%3A%20ANIME)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20idMal%0A%20%20%20%20%20%20startDate%20%7B%0A%20%20%20%20%20%20%20%20year%0A%20%20%20%20%20%20%20%20month%0A%20%20%20%20%20%20%20%20day%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20season%0A%20%20%20%20%20%20seasonYear%0A%20%20%20%20%20%20title%20%7B%0A%20%20%20%20%20%20%20%20native%0A%20%20%20%20%20%20%20%20romaji%0A%20%20%20%20%20%20%20%20english%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A).

**Comment by irevenko** [comment]
😁

**Comment by irevenko** [comment]
@soruly i have a question about image by upload endpoint
so previously i just sent json with base64 encoded image
but now it is form data why?

**Comment by soruly** [comment]
base64 encoding is 30-40% larger so it waste a lot more traffic than a form post in binary format. Aside from network traffic, it also saves CPU time encoding/decoding to/from base64. With binary format you can actually send a higher quality image under the same file size limit.

**Comment by irevenko** [comment]
someone migrated for me POG https://github.com/irevenko/what-anime-cli/pull/5
